project:
  type: website
  output-dir: docs

website:
  title: "R / Quarto Learning Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Bonnes_pratiques_en_R.qmd
        text: Guide

format:
  html:
    theme: cosmo
    toc: true
